### ISSUE TITLE
Missing json-loader in example

### ISSUE THREAD

**Issue by loiclacombe** [FormidableLabs/ecology#28]
Hi,
I've tried to use your tool, and I got this error:

```
ERROR in ./~/doctrine/package.json
Module parse failed: E:\dotnet\react\transatel-dropdown\node_modules\doctrine\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.unexpected (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1483:8)
    at Parser.pp.semicolon (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1976:8)
    at Parser.pp.parseStatement (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1754:188)
    at Parser.pp.parseBlock (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1991:21)
    at Parser.pp.parseStatement (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1735:19)
    at Parser.pp.parseTopLevel (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1648:21)
    at Parser.parse (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:1616:17)
    at Object.parse (E:\dotnet\react\transatel-dropdown\node_modules\webpack\node_modules\acorn\dist\acorn.js:882:44)
 @ ./~/doctrine/lib/utility.js 31:14-40
```

It means that it lacks a json-loader, and that is should be configured in webpack. It may be that one of the used libs changed a bit.

So here is the correct install command:
npm install -S babel babel-core babel-preset-es2015 babel-preset-react babel-loader raw-loader ecology react react-dom react-docgen webpack webpack-dev-server json-loader
And the associated webpack configuration:

```
module.exports = {
  devServer: {
    contentBase: __dirname,
    noInfo: false
  },
  output: {
    path: __dirname,
    filename: "main.js",
    publicPath: "/"
  },
  devtool: "source-map",
  entry: {
    app: ["./docs/docs.jsx"]
  },
  resolve: {
    extensions: ["", ".js", ".jsx"]
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        query: {
          presets: ["es2015", "react"]
        },
        exclude: /node_modules/
      },
    {test: /\.json$/, loader: "json"}
    ]
  }
};
```

If I got time on my hands, I will submit a pull request of the documentation.

Cheers!

**Comment by mdaxtman** [comment]
issue was resolved with [pull request #29](https://github.com/FormidableLabs/ecology/pull/29). Thank you for filing.
